import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Card from '@/components/Card'


export default function Home() {
  return (
    <>
      <Head>
        <title>site_react_v1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.Cardcontainer}>
          <Card/>
          <Card/>
          <Card/>
        </section>
      </main>
    </>
  )
}
